# Generated by Django 5.2.13 on 2026-05-06

from django.db import migrations, models


def migrate_existing_guidelines(apps, schema_editor):
    Guideline = apps.get_model("core", "Guideline")
    for guideline in Guideline.objects.all():
        content = getattr(guideline, "content", "") or ""
        media_url = getattr(guideline, "media_url", "") or ""
        guideline.short_description = content[:237] + "..." if len(content) > 240 else content
        guideline.detailed_tips = content
        guideline.youtube_url = media_url
        guideline.media_type = "YouTube" if media_url else "None"
        guideline.save(
            update_fields=[
                "short_description",
                "detailed_tips",
                "youtube_url",
                "media_type",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_guideline_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guideline",
            name="ai_eco_tip",
            field=models.TextField(blank=True, verbose_name="AI Eco Tip"),
        ),
        migrations.AddField(
            model_name="guideline",
            name="category",
            field=models.CharField(
                choices=[
                    ("Wet Waste", "Wet Waste"),
                    ("Dry Waste", "Dry Waste"),
                    ("Sanitary Waste", "Sanitary Waste"),
                    ("Special Waste", "Special Waste"),
                    ("General Eco Tips", "General Eco Tips"),
                ],
                default="General Eco Tips",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="guideline",
            name="detailed_tips",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="guideline",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="guideline",
            name="donts",
            field=models.TextField(blank=True, verbose_name="Don'ts"),
        ),
        migrations.AddField(
            model_name="guideline",
            name="dos",
            field=models.TextField(blank=True, verbose_name="Do's"),
        ),
        migrations.AddField(
            model_name="guideline",
            name="icon",
            field=models.CharField(default="\u267b", max_length=12),
        ),
        migrations.AddField(
            model_name="guideline",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="guideline",
            name="media_file",
            field=models.FileField(blank=True, upload_to="guidelines/"),
        ),
        migrations.AddField(
            model_name="guideline",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Image", "Uploaded image"),
                    ("Video", "Uploaded video"),
                    ("YouTube", "YouTube link"),
                ],
                default="None",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="guideline",
            name="recycling_tips",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="guideline",
            name="short_description",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="guideline",
            name="theme_color",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="guideline",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
        migrations.RunPython(migrate_existing_guidelines, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="guideline",
            name="content",
        ),
        migrations.RemoveField(
            model_name="guideline",
            name="media_url",
        ),
        migrations.AlterModelOptions(
            name="guideline",
            options={"ordering": ["display_order", "category", "title"]},
        ),
    ]
