# Generated by Django 5.2.13 on 2026-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_learning_hub_guidelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideline',
            name='badge_labels',
            field=models.CharField(blank=True, help_text='Comma-separated mini badges shown on the learning card.', max_length=180),
        ),
    ]
