# Generated by Django 5.2.13 on 2026-05-18 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_learning_hub_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='area_locality',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='profile',
            name='area_type',
            field=models.CharField(blank=True, choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='door_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must contain exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must contain exactly 6 digits.', regex='^\\d{6}$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_waste_category',
            field=models.CharField(blank=True, choices=[('Wet Waste', 'Wet Waste'), ('Dry Waste', 'Dry Waste'), ('Sanitary Waste', 'Sanitary Waste'), ('Special Waste', 'Special Waste')], max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='ward_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
