# Generated by Django 5.2.13 on 2026-06-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_area_locality_profile_area_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Duplicate Submission', 'Duplicate Submission')], default='Pending', max_length=40),
        ),
    ]
